name	= "One Click Wonder (T2/T3 Mex Support)"
author	= "BulletMagnet, Washy, Dragonfire"
uid		= "c5cc7241-d9f8-4b46-8662-ad130e426a4a"
version	= 4
description	= "Single-click on mass- and hydrocarbon-deposits to build them, and automatically rebuild destroyed buildings. Dragonfire: build t2/t3 mexes if available"
selectable	= true
enabled		= true
exclusive	= false
ui_only		= true
requires	= {}
requiresNames	= {}
conflicts		= {}
before			= {}
after			= {"156D4798-5C08-11DD-BEF3-1CB556D89593"}